package coolify

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
	"github.com/wappsdev/wapps-cli/internal/coolify"
)

var (
	imServerUUID string
	imOutputDir  string
)

var safeIdentifier = regexp.MustCompile(`[^a-zA-Z0-9_]+`)

var importAppCmd = &cobra.Command{
	Use:   "import-app",
	Short: "List Coolify apps on a server → emit Tofu import commands + HCL stubs",
	RunE: func(cmd *cobra.Command, args []string) error {
		token := os.Getenv("COOLIFY_API_TOKEN")
		if token == "" {
			return fmt.Errorf("COOLIFY_API_TOKEN not set")
		}

		c := coolify.New(getEndpoint(), token)
		apps, err := c.ListApplications()
		if err != nil {
			return err
		}

		_ = os.MkdirAll(imOutputDir, 0755)
		importsFile := filepath.Join(imOutputDir, "imports.sh")
		hclFile := filepath.Join(imOutputDir, "apps.tf")
		impf, err := os.Create(importsFile)
		if err != nil {
			return err
		}
		defer impf.Close()
		hclf, err := os.Create(hclFile)
		if err != nil {
			return err
		}
		defer hclf.Close()

		fmt.Fprintln(impf, "#!/usr/bin/env bash")
		fmt.Fprintln(impf, "# Generated by wapps coolify import-app — review before running.")
		fmt.Fprintln(impf, "set -e")
		fmt.Fprintln(impf, "")

		fmt.Fprintln(hclf, "# Generated stubs by wapps coolify import-app — fill in args from `tofu show <addr>` after import.")
		fmt.Fprintln(hclf, "")

		count := 0
		for _, a := range apps {
			// Coolify v4 nests server uuid under destination.server.uuid (not top-level).
			var srv string
			if dest, ok := a["destination"].(map[string]interface{}); ok {
				if server, ok := dest["server"].(map[string]interface{}); ok {
					srv, _ = server["uuid"].(string)
				}
			}
			if imServerUUID != "" && srv != imServerUUID {
				continue
			}
			uuid, _ := a["uuid"].(string)
			name, _ := a["name"].(string)
			if uuid == "" || name == "" {
				continue
			}
			id := safeIdentifier.ReplaceAllString(strings.ToLower(name), "_")
			if id == "" {
				id = fmt.Sprintf("app_%s", uuid[:8])
			}
			fmt.Fprintf(impf, "tofu import 'coolify_application.%s' '%s'\n", id, uuid)
			fmt.Fprintf(hclf, "# Imported from Coolify: %s (uuid=%s)\n", name, uuid)
			fmt.Fprintf(hclf, "resource \"coolify_application\" \"%s\" {\n", id)
			fmt.Fprintf(hclf, "  # Run: tofu import, then fill in args from `tofu show coolify_application.%s`\n", id)
			fmt.Fprintln(hclf, "}")
			fmt.Fprintln(hclf, "")
			count++
		}

		fmt.Printf("✓ Wrote %d imports to %s + HCL stubs to %s\n", count, importsFile, hclFile)
		return nil
	},
}

func init() {
	importAppCmd.Flags().StringVar(&imServerUUID, "server-uuid", "", "Filter by server UUID (empty = all)")
	importAppCmd.Flags().StringVar(&imOutputDir, "output-dir", "./.outputs/import", "Where to write imports.sh + apps.tf")
	CoolifyCmd.AddCommand(importAppCmd)
}
