package cmd

import "testing"

// Guards against accidentally removing the rootCmd.Version assignment.
// When Version is empty, cobra silently omits the --version flag — operators
// would see "unknown flag: --version" with no clue why.
func TestRootCmd_VersionFieldSet(t *testing.T) {
	if rootCmd.Version == "" {
		t.Errorf("rootCmd.Version must be non-empty so --version flag is generated by cobra")
	}
}

// Local builds (no GoReleaser ldflag) carry "dev" — support uses this
// signal to distinguish official releases from arbitrary local builds.
func TestVersion_DefaultIsDev(t *testing.T) {
	// We can't easily test the ldflag-injected case here (test binaries
	// don't carry the release ldflag), but we CAN assert the default
	// fallback so a future refactor doesn't silently clear it.
	//
	// Earlier this guard read `if Version != "dev" && Version == ""` which
	// is unsatisfiable (a string can't simultaneously be != "dev" and ==
	// "") — meaning the test could never fail and so the assertion was
	// load-bearing for nothing. Tightened to `Version == ""`.
	if Version == "" {
		t.Errorf("Version must default to a non-empty placeholder; got empty")
	}
}
